### ISSUE TITLE
Not seeing the downloaded images despite output showing 200 OK?

### ISSUE THREAD

**Issue by helpfulBro** [v12mike/fetch-external-images#3]
Output is when running the php download is : 

status OK 200 for 995 : http://i32.photobucket.com/albums/d24/hamiltw/1908packwood.jpg

But there is nothing in the /images/ext folder?

**Comment by v12mike** [comment]
Is that true for all images, or just that one?
Which platform are you running on?
Have you checked that the shell running the script has write permissions?

**Comment by helpfulBro** [comment]
It is all images.
Shared hosting
Perhaps that is the issue.

I was just running the php script via the browser, although it did create the /images/ext folder so I would assume it does have write permissions?
