### ISSUE TITLE
Regex img src URLs

### ISSUE THREAD

**Issue by Iveco** [v12mike/fetch-external-images#4]
extract_external_links.php

img src example: https://www.bing.com/th?id=ON.39C32F43EC4B01E928A7C0637186511F&pid=News&h=367&w=700

(phpBB 3.2 format)

will not be extracted by regex:

"if (preg_match_all('~<img src=\"(http[^\/]+?\/\/([^\/]+)?\/.+?[^\.]+?\.([a-z]+?))\">~i', $post_text, $matches))"

I've a lot more of these "dynamic image" urls which are not cached/harvested locally because they are not fetched, because this regex will fail.

I tried to modify it but later it requires tables filled like link and ext. Its a valid image within src="" or tag [img]src[/src].

Can you improve that the fetcher will really get all images between tags/srces - while ignoring the extensions and url format? That way it would support about 10-20% more images on my board which are currently not fetchable because of specified links. Maybe get rid of $link and $ext completely and just regex * between src="" and [img]src[/img] tags?

**Comment by v12mike** [comment]
I understand the problem and I will look into this, but due to other priorities, it will be at least several weeks before I can do anything about it,

**Comment by Leinad4Mind** [comment]
Shouldnt this code: ([a-z]+?) be instead ([A-Za-z]+)
